### ISSUE TITLE
Touchpad After sleep stop working

### ISSUE THREAD

**Issue by Ardentwheel** [Ardentwheel/OpenCore-Hasee-X57S1#2]
##  After sleep Touchpad stop working

As we change `SHPO (GPDI, Zero) -> SHPO (GPDI, One)` to made Touchpad worked,
there's still have warning on the log `sudo dmesg | grep -i voodoo`

> VoodooI2CControllerNub::pci8086,34e8 SSCN not implemented in ACPI tables
VoodooI2CControllerNub::pci8086,34e8 FMCN not implemented in ACPI tables

#### In OEM DSDT there's SSCN & FMCN
> If (USTP) {
        Scope (_SB.PCI0.I2C0) {
            Method (SSCN, 0, NotSerialized) { Return (PKG3 (SSH0, SSL0, SSD0)) }
            Method (FMCN, 0, NotSerialized) { Return (PKG3 (FMH2, FML2, FMD2)) }}}

### According #1 https://github.com/VoodooSMBus/VoodooRMI/issues/67#issuecomment-699558464
the problem seems to be the default clock speed timing of  I2C controller
but voodooi2c fine the SSCN & FMCN, 
so I change Method SSCN & FMCN to XSCN & XMCN, And add:
```
External (_SB_.PCI0.I2C3, DeviceObj)
Scope (_SB.PCI0.I2C3)
{
    Name (SSCN, Package (0x03) {
        0x01B0, 
        0x01FB, 
        0x1E
        })
    Name (FMCN, Package (0x03) {
        0x48, 
        0xA0, 
        0x1E
    })
}
```
#### warning on the log about not implemented in ACPI tables is gone, 
but after sleep Touchpad still stop working, maybe the value not right

### Thought Or Suggestion? 
@m0d16l14n1
@ben9923
@zhen-zen

**Comment by m0d16l14n1** [comment]
You can get the rid of that SSCN/FMCN warning if you set USTP to "One" + rename patch, that's how we did that with Ben. But still, there is a problem with touchpad after sleep-wake cycle for sure. I saw, that we have some serial timings for touchpad. Maybe we should play around them? 

![IMG_1457](https://user-images.githubusercontent.com/38903713/95691559-8f758180-0c28-11eb-92b6-f76769e2716f.JPG)

**Comment by m0d16l14n1** [comment]
Checked the polling mode - still no touchpad after sleep at all.

**Comment by m0d16l14n1** [comment]
Touchpad isn't fixed for that moment, but there is a way to make it work after sleep process. 

1. Disable SIP
2. sudo kextunload -b com.alexandred.VoodooI2CHID
sudo kextunload -b com.alexandred.VoodooI2C
3. Navigate to the directory with the kexts
sudo chown -R root:wheel VoodooI2C.kext VoodooI2CHID.kext
sudo kextutil -d VoodooI2C.kext VoodooI2CHID.kext

I will try to automate that process after sleep, to not to do that manually after every wake process. I will attach script, once it done.

**Comment by m0d16l14n1** [comment]
Big update! 

https://github.com/VoodooI2C/VoodooI2C/issues/399#issuecomment-757006967

**Comment by m0d16l14n1** [comment]
Fixed in https://github.com/VoodooI2C/VoodooI2CHID/pull/45
