### ISSUE TITLE
Question: Wakeup via PS/2

### ISSUE THREAD

**Issue by benbender** [Ardentwheel/OpenCore-Hasee-X57S1#5]
Hey,

I just saw the `Wake Up (PS/2 Keyboard) (Big Thanks to m0d16l14n1)`-claim and even If I'm on a Lenovo Thinkpad, it's one of the items of my 'nice-to-have'-list that I didn't knew it is even possible. Would you be so kind and give me a hint on how you managed to get that working? A hint in the right direction should be sufficient I think. Thanks in advance!

**Comment by m0d16l14n1** [comment]
Hey!

Nothing special here, it works by default on most of framebuffers exclude the default one for icelake. We still got problem with random lid sleep working (sometimes it's not sleeping from closing lid, but always wake if open it)

**Comment by m0d16l14n1** [comment]
I am not sure, but maybe _darkwake=?_ will help you?

**Comment by benbender** [comment]
Ah ok, I thought you did anything special to achive ps2-wake because it was named espacially but couldn't find anything. Thanks anyway!

A hint for the lidsleep: if its sometimes working and sometimes not, I would expect that the lid-close-event is there and you sometimes have `sleep preventers` from osx' perspective. Check with `sudo pmset -g assertionslog`. I would think of a bad usbmap-config or similar.

**Comment by m0d16l14n1** [comment]
> Ah ok, I thought you did anything special to achive ps2-wake because it was named espacially but couldn't find anything. Thanks anyway!
> 
> 
> 
> A hint for the lidsleep: if its sometimes working and sometimes not, I would expect that the lid-close-event is there and you sometimes have `sleep preventers` from osx' perspective. Check with `sudo pmset -g assertionslog`. I would most propably think of a bad usbmap-config or similar.

Thanks for the hint, will check it for sure

**Comment by benbender** [comment]
Youre welcome!

**Comment by m0d16l14n1** [comment]
@benbender hello and sorry for pinging, have a question about your thinkpad. How did you get hibernation 25 mode to work? Something special there? Also, how i can check if hibernation is working or not?

**Comment by benbender** [comment]
The process is documented in this thread (but vendor/laptop-specific): https://github.com/tylernguyen/x1c6-hackintosh/issues/44

For the "how to know if its working": set it up (without the lenovo-specific stuff) and test it via "sudo pmset -a hibernatemode 25 && pmset sleepnow"

**Comment by m0d16l14n1** [comment]
@benbender thanks for that information, will check if it gonna work for me or not. What about standby and autopoweroff? Should it be off or on?

**Comment by benbender** [comment]
Thats up to you. If you have your setup correct, it doesn't matter. But I'm personally no fan of hibernatemode 25 as it takes quite a while to wakeup - even if its working.

**Comment by m0d16l14n1** [comment]
@benbender so, better to try mode 3?

**Comment by benbender** [comment]
mode 3 is default on genuine macs, yes. 

````
     hibernatemode = 3 by default on portables. The system will store a copy
     of memory to persistent storage (the disk), and will power memory during
     sleep. The system will wake from memory, unless a power loss forces it to
     restore from hibernate image.
````

Source: `man pmset`
