### ISSUE TITLE
LID sleep issue / Not going to sleep if lid is closed

### ISSUE THREAD

**Issue by m0d16l14n1** [Ardentwheel/OpenCore-Hasee-X57S1#7]
Was just curious, why lid sleep is not working sometimes, so I did a little research with my system. 

Here is the log from 2 different boots: 

1) LID is NOT working

`
[   24.057541]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed **[\134_SB.PCI0.LPCB.H_EC.ECRD] (Node ffffff937301cd50)[\134_SB.PCI0.LPCB.H_EC.ECRD]** (Node ffffff937301cd50), AE_AML_OPERAND_TYPE, AE_AML_OPERAND_TYPE (20160930/psparse-632)
[   24.057553]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed **[\134_SB.PCI0.LPCB.H_EC.LID0._LID]** (Node ffffff937301b990)**[\134_SB.PCI0.LPCB.H_EC.LID0._LID]** (Node ffffff937301b990), AE_AML_OPERAND_TYPE, AE_AML_OPERAND_TYPE (20160930/psparse-632)
[   24.087987]: loadPrefs: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2-9e5-747-b3422a8f61594f46 using new keyACPI Error: ACPI Error: Needed Integer/Buffer/String/Package/Ref/Ddb], found [Mutex] ffffff9372fdff00Needed Integer/Buffer/String/Package/Ref/Ddb], found [Mutex] ffffff9372fdff00 (20160930/exresop-758)
[   24.089307]: ACPI Exception: AE_AML_OPERAND_TYPE, ACPI Exception: AE_AML_OPERAND_TYPE, While resolving operands for [Store]While resolving operands for [Store] (20160930/dswexec-570)
[   24.089463]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed [\134_SB.PCI0.LPCB.H_EC.ECRD] (Node ffffff937301cd50)[\134_SB.PCI0.LPCB.H_EC.ECRD] (Node ffffff937301cd50), AE_AML_OPERAND_TYPE, AE_AML_OPERAND_TYPE (20160930/psparse-632)
[   24.089503]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed [\134_SB.PCI0.LPCB.H_EC.LID0._LID] (Node ffffff937301b990)[\134_SB.PCI0.LPCB.H_EC.LID0._LID] (Node ffffff937301b990), AE_AML_OPERAND_TYPE, AE_AML_OPERAND_TYPE (20160930/psparse-632)
[   24.090386]: ACPI Error: ACPI Error: Needed Integer/Buffer/String/Package/Ref/Ddb], found [Mutex] ffffff9372fdff00Needed Integer/Buffer/String/Package/Ref/Ddb], found [Mutex] ffffff9372fdff00 (20160930/exresop-758)
[   24.090426]: ACPI Exception: AE_AML_OPERAND_TYPE, ACPI Exception: AE_AML_OPERAND_TYPE, While resolving operands for [Store]While resolving operands for [Store] (20160930/dswexec-570)
[   24.090592]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed [\134_SB.PCI0.LPCB.H_EC.ECRD] (Node ffffff937301cd50)[\134_SB.PCI0.LPCB.H_EC.ECRD] (Node ffffff937301cd50), AE_AML_OPERAND_TYPE, AE_AML_OPERAND_TYPE (20160930/psparse-632)
[   24.090630]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed [\134_SB.PCI0.LPCB.H_EC.LID0._LID] (Node ffffff937301b990)[\134_SB.PCI0.LPCB.H_EC.LID0._LID] (Node ffffff937301b990), AE_AML_OPERAND_TYPE, AE_AML_OPERAND_TYPE (20160930/psparse-632)
[   32.360421]: AGDCC: Unauthorized client 'PerfPowerService' (IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebufferController/IntelFBClientControl)memorystatus: set assertion priority(3) target setoken:319
`

2) LID is working like it should (waking from sleep, going to sleep well)

Nothing special about _LID or ECRD stuff. 

I will attach full logs. So, it's seems that we need somehow patch it to make it working stable, as it should. 

[LID is WORKING.log](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/files/5579156/LID.is.WORKING.log)
[LID not working.log](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/files/5579157/LID.not.working.log)

**Comment by m0d16l14n1** [comment]
Also, there is some ACPI errors related to battery patch > need to fix somehow "Mutex" stuff with SSDT (i found only DSDT patching methods, not SSDT). 

@Ardentwheel check on your laptop, do you have the same issue or not?

**Comment by Ardentwheel** [comment]
there is no error is my dsdt patch
![截屏2020-11-28 下午7 55 25](https://user-images.githubusercontent.com/8460881/100514945-b88baa80-31b3-11eb-9d71-1006edcd4b7b.png)

**Comment by m0d16l14n1** [comment]
@Ardentwheel i wasn't talking about error in SSDT patch, i was talking about ACPI log errors (on booting, not in SSDT files)
Also i am curious about LID more then battery, because battery is working okay.

**Comment by m0d16l14n1** [comment]
Found the "same" issue in another hackintosh repository (big thanks @kasti0 for that SSDT and fix). Just add that SSDT + rename patch in ACPI > Patch
_LID to XLID
Find: 5F4C4944 00
Replace: 584C4944 00
+ SSDT
[SSDT-LID.aml.zip](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/files/5760943/SSDT-LID.aml.zip)

Now LID is working stable even after reboot from Windows, still sometimes i see those ACPI warnings in logs, but now issue is gone even with those warning in log - lid is working stable as it should, heh. 

@kasti0, thanks again!

**Comment by kasti0** [comment]
Glad my patch helped you! Funny that it works on a completely different laptop. Must be a bug in the ACPI code
